### ISSUE TITLE
What Voltage and Current to run at?

### ISSUE THREAD

**Issue by Sherene11** [daniel-frenkel/udemy#1]
Hi, what DC Voltage and current should ESP32 DevKitC and BIGTREETECH TMC2209 V1.2 run at? Are there any particular stepper motors you recommend?

**Comment by daniel-frenkel** [comment]
The TMC2209 can run up to 2A, but I would limit it to 1.2A unless you can add active cooling. The higher the current the hotter it gets. 

Voltage is directly proportional to the maximum speed of the motor as well as the resistance of the motor windings. 

A good place to start is on [Lin Engineering](https://www.linengineering.com/products/stepper-motors/hybrid-stepper-motors/4418-series) because they provide really nice torque and speed curves for their motors. 

Stepper motor create max torque at standstill. The faster you turn them, the less torque they provide which means you need to increase the voltage as you increase the speed in order to maintain torque. But depending on the motor you own, you might need more voltage or more current to achieve the same speed and torque. Play around with the torque curves above to see what I mean.
